app = "name-optimizer-backend"
primary_region = "ams"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/api/health"

[processes]
  app = "node server.js"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1 